In [3]:
import numpy as np
from tensorflow.keras.models import Sequential  # 여기서 가져와야 합니다
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [5]:
docs = [ 'additional income',
         'best price',
         'big bucks',
         'cash bonus',
         'earn extra cash',
         'spring savings certificate',
         'valero gas marketing',
         'all domestic employees',
         'nominations for oct',
         'confirmation from spinner']

labels = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [7]:
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print("인코딩된 문서:", encoded_docs)

인코딩된 문서: [[15, 46], [37, 22], [46, 31], [42, 11], [29, 32, 42], [23, 8, 14], [5, 21, 49], [9, 33, 4], [21, 12, 31], [22, 18, 34]]


In [8]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print("\n패딩된 문서:\n", padded_docs)

model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))


패딩된 문서:
 [[15 46  0  0]
 [37 22  0  0]
 [46 31  0  0]
 [42 11  0  0]
 [29 32 42  0]
 [23  8 14  0]
 [ 5 21 49  0]
 [ 9 33  4  0]
 [21 12 31  0]
 [22 18 34  0]]


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [9]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(padded_docs, labels, epochs=50, verbose=0)

loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('\n정확도=', accuracy)


정확도= 1.0


In [10]:
test_doc = ['big income']
encoded_docs_test = [one_hot(d, vocab_size) for d in test_doc]
padded_docs_test = pad_sequences(encoded_docs_test, maxlen=max_length, padding='post')

print("\n'big income' 예측 결과:", model.predict(padded_docs_test))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

'big income' 예측 결과: [[0.5687552]]
