In [ ]:
path='/content/drive/MyDrive/Colab Notebooks/titanic.csv'

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv(path)       # CSV → DataFrame 데이터프레임으로 읽기


print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [ ]:
df.isnull().sum()

,0
PassengerId,0
Survived,0
Pclass,0
Name,0
Sex,0
Age,177
SibSp,0
Parch,0
Ticket,0
Fare,0


In [ ]:


# 2. 전처리 (한 번에 실행)
df['Sex'] = df['Sex'].map({'female': 0, 'male': 1})
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# 3. 원-핫 인코딩
df = pd.get_dummies(df, columns=['Embarked'])

# 4. X, y 만들기 (drop에 Embarked 없는 거 확인!)
y = df['Survived']
X = df.drop(['Name', 'Ticket', 'Cabin', 'Survived', 'PassengerId'], axis=1)

# 5. 확인
X.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,3,1,22.0,1,0,7.2500,False,False,True
1,1,0,38.0,1,0,71.2833,True,False,False
2,3,0,26.0,0,0,7.9250,False,False,True
3,1,0,35.0,1,0,53.1000,False,False,True
4,3,1,35.0,0,0,8.0500,False,False,True


In [ ]:
y.value_counts()

,count
Survived,
0,549
1,342


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

# Build a logistic regression classifier and predict
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))

# precision, recall, f1-score, macro/weighted avg가 한 번에 나옵니다.
print("\n--- 상세 분류 보고서 (Classification Report) ---")
print(classification_report(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.7937219730941704
[[116  23]
 [ 23  61]]

--- 상세 분류 보고서 (Classification Report) ---
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       139
           1       0.73      0.73      0.73        84

    accuracy                           0.79       223
   macro avg       0.78      0.78      0.78       223
weighted avg       0.79      0.79      0.79       223



In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# Build a decision tree classifier and predict

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

# precision, recall, f1-score, macro/weighted avg가 한 번에 나옵니다.
print("\n--- 상세 분류 보고서 (Classification Report) ---")
print(classification_report(y_test, pred_lr))


--- Decision Tree Classifier ---
0.7623318385650224
[[113  26]
 [ 27  57]]

--- 상세 분류 보고서 (Classification Report) ---
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       139
           1       0.73      0.73      0.73        84

    accuracy                           0.79       223
   macro avg       0.78      0.78      0.78       223
weighted avg       0.79      0.79      0.79       223



In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

# precision, recall, f1-score, macro/weighted avg가 한 번에 나옵니다.
print("\n--- 상세 분류 보고서 (Classification Report) ---")
print(classification_report(y_test, pred_lr))


--- Radom Forest ---
0.8475336322869955
[[126  13]
 [ 21  63]]

--- 상세 분류 보고서 (Classification Report) ---
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       139
           1       0.73      0.73      0.73        84

    accuracy                           0.79       223
   macro avg       0.78      0.78      0.78       223
weighted avg       0.79      0.79      0.79       223

